#config.yml

#是否启用记忆功能(不填默认为false)
Enable_SQLite: false

#功能介绍:
#启用记忆功能后，插件卸载时将自动保存资源点信息，并在下一次生效时重启资源点；
#禁用记忆功能后，插件卸载时会将资源点连带删除，下次重启需要手动再次部署资源点。


#Tips:
#  1、数据库遭到污染或损坏时，可以将以上选项更改为false,重载插件时将会清空数据库
#  2、热重载插件可以将所有资源点同步启动


#[Warning!]
#请勿尝试直接修改目录下的database.db文件，否则可能发声严重错误！！！
#任何对资源点的修改，应该使用本插件提供的接口
#如果迫不得已需要格式化数据库，可以直接删除数据库文件，或者关闭记忆功能，插件将自动进行格式化。